name: alpha_rubiks_cube
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipython=8.7.0
  - numpy=1.23.4
  - pip=22.3.1
  - pytest=7.1.2
  - python=3.10.8
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - jupyterlab=3.5.0
  - matplotlib=3.6.2
  - scipy=1.9.3
  - k3d=2.15.2
